### ISSUE TITLE
Exhibitors prospectus in better location

### ISSUE THREAD

**Issue by dmusican** [sigcsets/sigcse2017#13]
The exhibitors' prospectus is now up (thank you!), but in very hard to find "Home" menu. In SIGCSE 2015, it was under a "sponsors & exhibitors" menu. Can you repeat?

**Comment by s-edwards** [comment]
I agree.  We need to remove the "Home" menu entirely, since the logo already links to the home page, and the other two entries belong elsewhere.  We should have a top-level entry for sponsors/exhibitors, but part of the problem is that "sponsors & exhibitors" is a bit too large/long, and just "sponsors" may not convey enough (similarly for "exhibitors").  You could always start with "sponsors/exhibits" and we can word-smith it later.

Or, Dave, would you prefer to just have something prominent on the home page instead of in the menu system?

**Comment by dmusican** [comment]
> Or, Dave, would you prefer to just have something prominent on the home page instead of in the menu system?

I'm flexible. I just want to make sure the exhibitors can easily find the info.
